#!/bin/bash
# 从 Sketchfab 下载静态资产的辅助脚本
# 注意：需要手动获取下载链接

echo "============================================================"
echo "Sketchfab 资产下载指南"
echo "============================================================"
echo ""
echo "由于 Sketchfab 需要登录和手动操作，请按以下步骤："
echo ""
echo "1. 访问 https://sketchfab.com/"
echo "2. 搜索对应的3D模型（如 'bed', 'chair', 'sofa'）"
echo "3. 筛选：免费 + CC BY 4.0 许可"
echo "4. 下载 GLB 格式"
echo "5. 将文件重命名并放置到对应文件夹"
echo ""
echo "推荐搜索关键词："
echo "  - Bed: 'bed 3d model free'"
echo "  - Chair: 'chair 3d model free'"
echo "  - Sofa: 'sofa 3d model free'"
echo "  - Table: 'dining table 3d model free'"
echo ""
echo "文件放置位置："
echo "  infinigen/assets/static_assets/source/Bed/bed_standard.glb"
echo "  infinigen/assets/static_assets/source/Chair/chair_standard.glb"
echo "  infinigen/assets/static_assets/source/Sofa/sofa_standard.glb"
echo "  infinigen/assets/static_assets/source/Table/table_standard.glb"
echo ""
echo "下载后运行验证："
echo "  python tools/preprocess_static_assets.py"
echo ""
echo "============================================================"
